### ISSUE TITLE
Error when importing Python-Audio

### ISSUE THREAD

**Issue by MrMho** [bastibe/Python-Audio#3]
Hi, 
I use Windows 10 and Python 2.7.13 (Anaconda 4.3.1, 64-bit). When I try to import Python-Audio like this
`import pythonaudio as pa`
Python raises an error message saying:
```
File "C:\Users\[...]\Anaconda2\lib\site-packages\pythonaudio\mediafoundation.py", line 192
   raise TypeError(f'Invalid kind: {kind}')
```

**Comment by bastibe** [comment]
That's intriguing. Apparently your system has a device that is neither a `microphone` nor a `speaker`. I didn't know that could happen. 

Can you tell me what the actual error message says? Also, can you tell me the complete stack trace?

**Comment by MrMho** [comment]
Ah, sorry. I should have included the actual error message in my first post. Anyways, here comes the complete stack trace. I hope that this is what you meant.  
````
Traceback (most recent call last):
  File "[...]pythonaudio_test.py", line 4, in <module>
    import pythonaudio as pa
  File "C:\Users\[...]\Anaconda2\lib\site-packages\pythonaudio\__init__.py", line 8, in <module>
    from pythonaudio.mediafoundation import *
  File "C:\Users\[...]\Anaconda2\lib\site-packages\pythonaudio\mediafoundation.py", line 192
    raise TypeError(f'Invalid kind: {kind}')
                                          ^
SyntaxError: invalid syntax
````

**Comment by bastibe** [comment]
Thank you! It appears that you are not running Python 3.6. At the moment, Python 3.6 is required. Sorry about that. I should have realized that earlier.

**Comment by MrMho** [comment]
Ok, I see. Thanks for the quick reply.
